### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by jalalmanafi** [gigantz/reactend-template#1]
Hi , need roadmap for repository or any design

**Comment by jalalmanafi** [comment]
Hi @gigantz , i am waiting for your response

**Comment by gigantz** [comment]
Hi Jalal, I guess this is about reactend itself not template?
There's a [roadmap related issue](https://github.com/reactend/reactend-express/issues/4) I created a while ago.
Currently I'm out of maintenance, but feel free to suggest your roadmap or any another ideas about it.

**Comment by jalalmanafi** [comment]
Hi @gigantz , oh i mean i want to improve firstly frontend side , but i didn't know you are out of maintenance

**Comment by gigantz** [comment]
I'm planning to get back to maintain it and add client side support as well. But currently I'm away unfortunately.
